### ISSUE TITLE
Need Code Explanation

### ISSUE THREAD

**Issue by baskaran-radhakrishnan-10** [TheCK/codeChallenges#1]
Hello brother,

I just gone through code of **"Predict the Number"**.

But i don't understand , why you have used 

1.) Right Shift to find out the depth.
2.) what is the need of depth number.

Please kindly provide your explanation.

Thanks and Regards,
Baskaran Radhakrishnan.

**Comment by TheCK** [comment]
Namaste,

1) The getLog function just calculates the log to base 2 by counting how often you can shift the number right by one bit before it becomes 0. (Shifting right basicly divides by 2, but is much faster)

2) "depth" is just the number of steps that is needed to create the sequence of the required length. Since the length of the sequence doubles with every step, the number of steps needed is log_2.

Then depth is used to recursively calculate just the slice of the sequence that is needed.

Hope this helps, and good luck with your job interview (I assume)

**Comment by baskaran-radhakrishnan-10** [comment]
Thank you brother.
